#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys

# Description
# * Time complexity:
# * Space complexity:
def isEnableDrive(energy, cost):
    # TODO implement your solution to here.
    l = len(energy)
    e =0
    for i in range(l):
        for j in range(l):
            e+=energy[(i+j)%l]
            e-=cost[(i+j)%l]
            if e < 0:
                break;
        if e>=0 : return i
            

    return -1 

if __name__ == '__main__':
    T = int(sys.stdin.readline())

    for i in range(T):
        N = int(sys.stdin.readline())
        E = [int(x) for x in sys.stdin.readline().strip().split(' ')]
        C = [int(x) for x in sys.stdin.readline().strip().split(' ')]
        print(isEnableDrive(E, C))
